### PR TITLE
refactor: article data (filter articles to get true articles) #219

### PR DESCRIPTION
**Pull request by blessingtutka**
### Description

Décrivez brièvement l'objectif de cette demande d'extraction.

### Changements Effectués

Fournissez un aperçu concis des changements que vous avez effectués.

### Liste de Vérification

- [ ] Tester les changements localement.
- [ ] Le code respecte les normes du projet.

Merci !

### CODE REVIEW

**Comment by CREDO23** [comment]
@blessingtutka this PR is intended to fix which issue ?

**Comment by blessingtutka** [comment]
@CREDO23 
The description of the card was only for french wiki I have fix it do that
it can get description for all Wiki's.

**Comment by blessingtutka** [comment]
@Bam92  @CREDO23  @JoeMakuta 
I am waiting for you to approve my PR so that I can make another for PR

**Comment by Bam92** [comment]
Sorry @blessingtutka for the late answer here. Can you just fix conflicts?

**Comment by blessingtutka** [comment]
@Bam92  Got it

**Comment by blessingtutka** [comment]
@Bam92 Done

**Comment by Bam92** [comment]
Thanks, @blessingtutka!

Is there any associated issue for this? If so, do give the id.

**Comment by blessingtutka** [comment]
@Bam92 

#219

**Pull request merged**
