### PR TITLE
refactor: Separation of Concerns && code refactoring

### PR DESCRIPTION
**Pull request by blessingtutka**
### Description

Décrivez brièvement l'objectif de cette demande d'extraction.

### Changements Effectués

Fournissez un aperçu concis des changements que vous avez effectués.

### Liste de Vérification

- [ ] Tester les changements localement.
- [ ] Le code respecte les normes du projet.

Merci !

### CODE REVIEW

**Comment by blessingtutka** [comment]
I've done some components separation of concerns like ( ArticleForm, ArticleView, Top Africa)
I've add fetchloation API result form separation of concern.
I've refactor some css style and the **top Africa** page style and functionalities

**Comment by Bam92** [comment]
@blessingtutka thank you for your PR. I noticed that you don't have the latest version of the app. Can you make sure you have it locally?

This is how it looks like
Screenshot 2024-06-08 at 22 29 31

Your version is like this (you still have underscore in the titles)
Screenshot 2024-06-08 at 22 29 41

Update your PR and let me know.

**Comment by blessingtutka** [comment]
@Bam92  Some titles are not displaying when I pull the latest change that's why I remove the function that remove the underscore but I'll try to find another that do it better.

This is what I found: `{article?.includes('_') && (article = article.replace(/_/g, ' '))}`
 (please look at the first article)
Capture d’écran (2927)

**Comment by blessingtutka** [comment]
@Bam92 
Fix it with this :
`{article?.includes('_') ? article.replace(/_/g, ' ') : article}`
Now everything is fine

**Comment by Bam92** [comment]
@blessingtutka thank you for the update. Can you send me the screenshot of the hero section? It's written in Français "Veillez remplir..." not "Fill all fields".

**Comment by blessingtutka** [comment]
@Bam92 
 I'm update but for some pages, I accept my change on the merge editor.
 
Capture d’écran (2931)

**Pull request merged**
