### PR TITLE
Add errors toast from all errors

### PR DESCRIPTION
**Pull request by land-bit**
### Description

Résolution des issues #208 et #175 

### Changements Effectués

Add toast  error for geolocalisation, for fetch background image and fetch data from API

### Liste de Vérification

- [X] Tester les changements localement.
- [ ] Le code respecte les normes du projet.

Merci !

### CODE REVIEW

**Comment by land-bit** [comment]
@Bam92 et @CREDO23 , J'ai fini l'issue des toast

**Comment by Bam92** [comment]
@land-bit I can only see toast for #175. Can you check if you also fixed #208. Or can edit your PR so that we only consider #175 for now?

**Comment by land-bit** [comment]
@Bam92 , I just fixed all the toasts (from #175 and #208 )

**Comment by Bam92** [comment]
@land-bit I've merged, but I noticed it only fixes #208. So, I only mentioned #175

**Pull request merged**
